### ISSUE TITLE
Is it possible to save complex data? Like an array of objects?

### ISSUE THREAD

**Issue by freakynit** [TileDB-Inc/TileDB-MariaDB#308]
Something like for example: 
```javascript
[
	{
		"city": "",
		"country": "",
		"name": ""
	},
	...
	...
]
```

If not, any suggestions on how to model such a structure?

**Comment by DimitrisStaratzis** [comment]
Hi @freakynit ,

Thank you for raising this issue. Currently, MariaDB doesn’t support fixed-size (greater than one value) or variable-length types. There isn’t a native “array” type to which we can convert this value in MariaDB. Here are three options for your use case:

## Option 1:
You can encode your attribute values in a CSV or JSON format and store them as a string. This is probably the simplest solution, but it will introduce the overhead of conversion from JSON/CSV.

## Option 2:
We recently introduced the ability to store multi-valued fixed-size length attributes in TileDB-MariaDB as blobs. The way this works is that you report the attribute as a BLOB type, and you save the values as a raw sequence of bytes. In fact, if you create a TileDB array from another API or integration and set an attribute as multi-valued and fixed-size, Mytile will automatically read that attribute as a BLOB type. This solution requires that the values you store are of the same length so that you can later decode them. For example, it would work if you use three-letter short names for a country or city (ATH, GRE, etc.), so it has some limitations. An example of this can be found in one of our tests here:
[test](https://github.com/TileDB-Inc/TileDB-MariaDB/blob/master/mysql-test/mytile/t/multi_value_fixed_length.test), [result](https://github.com/TileDB-Inc/TileDB-MariaDB/blob/master/mysql-test/mytile/r/multi_value_fixed_length.result)

## Option 3:
You can report each value as a separate column in MariaDB, i.e., ```attribute_1_value_1```, ```attribute_1_value_2```, ```attribute_1_value_3```. This requires that the number of generated fields is known, which I believe is the case in your data.

I hope this helps. Let me know if you need further assistance.

Best,
Dimitris (edited)

**Comment by freakynit** [comment]
Thanks @DimitrisStaratzis . This helps a lot..
