### ISSUE TITLE
vcpkg port

### ISSUE THREAD

**Issue by niclar** [TileDB-Inc/TileDB-MariaDB#381]
Hi, a vcpkg port of this library would greatly simplify integration and distribution for us and the rest of the community and further drive adaptation I would think. Is this on your roadmap ? -Maintaining an unofficial cross platform port (attached) of this library is quite an headache...

Best
[mariadb.zip](https://github.com/user-attachments/files/17062472/mariadb.zip)

**Comment by teo-tsirpanis** [comment]
Thanks for the suggestion. Because TileDB-MariaDB cannot be built as a standalone library but only within a build of MariaDB, this would be tantamount to making a vcpkg port for MariaDB as a whole, and because MariaDB is not a library but a database server, vcpkg is not a fitting way to build it, and therefore we are not planning to do this.

You can take a look at the repository's [Dockerfiles](https://github.com/TileDB-Inc/TileDB-MariaDB/tree/master/docker) for help with how to build TileDB-MariaDB.

**Comment by niclar** [comment]
"tantamount to making a vcpkg port for MariaDB as a whole" not really, just the bare minimum and not a full standalone port, as in the attached mytile port. Also compare to the libmariadb port already in vcpkg

**Comment by teo-tsirpanis** [comment]
We can't draw parallels with the `libmariadb` port because it is a client library to MariaDB, while TileDB-MariaDB is a server-side component.
